[package]
name = "bignumber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "0.13.2"
bigint = "4"
schemars = "0.7"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "0.13.2"
